server:
  port: 8080
  servlet:
    context-path: /flashcard


spring:
  application:
    name: flastcard
  datasource:
    url: "jdbc:mysql://localhost:3307/flastcard_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  signerKey: "d9f171a418ef107b63d2f49e8ac54ad234d15ef3d91b951da896c984b0e0d9d5"